//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_BaiHatEntities1 : DbContext
    {
        public QL_BaiHatEntities1()
            : base("name=QL_BaiHatEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Album> tbl_Album { get; set; }
        public virtual DbSet<tbl_BaiHat> tbl_BaiHat { get; set; }
        public virtual DbSet<tbl_NhacSi> tbl_NhacSi { get; set; }
        public virtual DbSet<tbl_TheLoai> tbl_TheLoai { get; set; }
    }
}
