//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BaiHat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BaiHat()
        {
            this.tbl_Album = new HashSet<tbl_Album>();
        }
    
        public int MaBH { get; set; }
        public string TenBH { get; set; }
        public int MaTL { get; set; }
        public int MaNS { get; set; }
    
        public virtual tbl_NhacSi tbl_NhacSi { get; set; }
        public virtual tbl_TheLoai tbl_TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Album> tbl_Album { get; set; }
    }
}
